version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka
    depends_on:
        - zookeeper
    ports:
        - 29092:29092
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  actions-trigger:
    image: mheers/kafka-gh-actions-trigger:latest
    environment:
      - "GITHUB_TOKEN=${GITHUB_TOKEN}"
      - "REPO_ORG=${REPO_ORG}"
      - "REPO_NAME=${REPO_NAME}"
      - "KAFKA_BROKER=kafka:9092"
      - "KAFKA_TOPIC=${KAFKA_TOPIC}"
    depends_on:
        - kafka
